<pre class='metadata'>
Title: User Agent Image Replacement API
Shortname: ua-image-replacement
Level: None
Status: w3c/UD
Repository: explainers-by-googlers/ua-image-replacement
URL: https://explainers-by-googlers.github.io/ua-image-replacement
Editor: Jeremy Roman, Google https://google.com, jbroman@google.com
Abstract: Simple API for allowing authors to respond to browser features which edit images in the page
Markup Shorthands: markdown yes, css no
Complain About: accidental-2119 yes, missing-example-ids yes
Assume Explicit For: yes
Die On: warning
WPT Path Prefix: TODO-API-LABEL
WPT Display: closed
Include MDN Panels: if possible
Include Can I Use Panels: yes
</pre>

Introduction {#intro}
=====================

For now, see the <a href="https://github.com/explainers-by-googlers/ua-image-replacement">explainer</a>.

See [https://garykac.github.io/procspec/](https://garykac.github.io/procspec/),
[https://dlaliberte.github.io/bikeshed-intro/index.html](https://dlaliberte.github.io/bikeshed-intro/index.html),
and [https://speced.github.io/bikeshed/](https://speced.github.io/bikeshed/) to get started on your
specification.
